language: java
script: mvn test package
jdk:
  - openjdk7
branches:
  only:
    - master
env:
 global:
   - "ARTIFACTS_AWS_REGION=eu-west-1"
   - "ARTIFACTS_S3_BUCKET=github-files"
   - secure: "aPnDBR5s/hGaDRvspFgeLA2QcH3p79hNwZG8XgMSi64hothHuaLaseNtNafe\nbKeILA0jT4DmukdA9b6fvmvsmDz/5g0EpRdT34RWNc+8Lg2Tq42Tvq+Qf8tZ\nzcnwyc9UnRHuvqEhbNWXE1kdIinq5hdvTC+QAJRB5XVrDPBHfgY="
   - secure: "FBa+uTJvpypvzmGCkNJHj8C0yQ7OqpH4PbKqDEY4cyqjqvXAnp9S1Djzar2+\nybJWoNk2h2S9k/kOf81xqid8CDWcn3UIC5jJtbgAGWk8sxcJ0TIUjJSNI5Pr\njgYu9CMJVPn6HV0k+NT7hVlirlW92ZMyglgSQCbpJpwVVObHUHA="
before_script:
   - "gem install travis-artifacts"
after_success:
  - "travis-artifacts upload --path svn2git-gui/target/svn2git.jar --target-path svn2git"